#lang racket
(define (sum-of-squares-max a b c)
  (define (square x)
    (* x x))
  (cond ((and (> a b)
              (> a c)) (+ (square a)
                          (square (max b c))))
        ((and (> b a)
              (> b c)) (+ (square b)
                          (square (max a c))))
        (else (+ (square c)
                 (square (max a b))))))

(sum-of-squares-max 1 2 3)
(sum-of-squares-max 2 3 1)